version: '3'
services:
  deepvein:
    container_name: footauth2025
    ipc: host
    restart: unless-stopped
    stdin_open: true
    tty: true
    build:
      dockerfile: ./Dockerfile
    volumes:
      - .:/root/code
      - /mnt/cluster/nbl-datasets/fingervein/Foot_Print/Training:/root/code/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - utility
                - compute

